"""Added news feed id to office table

Revision ID: 2826df0a03df
Revises: 93df060e8edf
Create Date: 2025-02-24 11:42:42.517315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2826df0a03df'
down_revision = '93df060e8edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('news_feed_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'news_feed_id')
    # ### end Alembic commands ###
