"""Added ministers_history table

Revision ID: 3efbeba35228
Revises: be45c7e8cff0
Create Date: 2024-10-31 12:52:38.256291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efbeba35228'
down_revision = 'be45c7e8cff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministers__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ministers__history')
    # ### end Alembic commands ###
