"""Added party column to ministers_history table

Revision ID: 3f82e60a65e0
Revises: 3efbeba35228
Create Date: 2024-10-31 13:21:00.834449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f82e60a65e0'
down_revision = '3efbeba35228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministers__history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('party', sa.String()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ministers__history', schema=None) as batch_op:
        batch_op.drop_column('party')

    # ### end Alembic commands ###
