"""add is_shown column to office table

Revision ID: 66f0318704f9
Revises: 2e642647543f
Create Date: 2025-05-14 11:30:01.073739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f0318704f9'
down_revision = '2e642647543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexes', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('indexes_data', schema=None) as batch_op:
        batch_op.alter_column('index_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('ministers_history', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('office_branches', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shown', sa.Boolean(), nullable=True))
        batch_op.alter_column('minister_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.alter_column('twitter_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.alter_column('twitter_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.alter_column('minister_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_shown')

    with op.batch_alter_table('office_branches', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ministers_history', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('indexes_data', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('index_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('indexes', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
