"""Added new start and finish dates to non-parlament members

Revision ID: 8bd75a5978ac
Revises: fe75f0961c42
Create Date: 2024-11-29 02:02:50.444602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd75a5978ac'
down_revision = 'fe75f0961c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_parliament_members', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('non_parliament_members', sa.Column('finish_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_parliament_members', 'finish_date')
    op.drop_column('non_parliament_members', 'start_date')
    # ### end Alembic commands ###
