"""Add OfficeBranch table

Revision ID: 93df060e8edf
Revises: c0b671307013
Create Date: 2025-01-03 17:56:43.305678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93df060e8edf'
down_revision = 'c0b671307013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_branches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('office_id', sa.BigInteger(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_branches')
    # ### end Alembic commands ###
