"""Added appointed_by column to nonparliamentmembers table

Revision ID: b21931b04053
Revises: 8bd75a5978ac
Create Date: 2024-12-06 02:30:50.018240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21931b04053'
down_revision = '8bd75a5978ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('non_parliament_members', sa.Column('appointed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('non_parliament_members', 'appointed_by')
    # ### end Alembic commands ###
