"""added sourse to index list

Revision ID: c0b671307013
Revises: b21931b04053
Create Date: 2024-12-17 01:43:26.059824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b671307013'
down_revision = 'b21931b04053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexes', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indexes', 'source')
    # ### end Alembic commands ###
